filetype plugin indent on
syntax on
set nu bs=2 sw=2 et ts=2 sts=2 rnu showcmd ar aw mouse=a nohls
set background=dark
setlocal cindent cino=j1,(0,ws,Ws
set timeoutlen=3000 ttimeoutlen=100
“ :cw :cn :cp
set makeprg=g++\ -std=c++11\ -D__DEBUG\ -fsanitize=address\ -g\ -o\ %<\ %
